name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🔠 Lint project
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 📦 Install browsers
        run: pnpm playwright install chromium --with-deps

      - name: 💪 Type check
        run: pnpm test:types

      - name: 🧪 Unit test
        run: pnpm test:unit

      - name: 🏃 Component tests
        run: pnpm test:nuxt

  browser:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/playwright:v1.62.1-noble

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2
        with:
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🖥️ Test project (browser)
        run: pnpm test:browser
